import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FileContentCreate {

	public static void main(String[] args) {
		fileWriter(fileCreator(askForFileName()), askForContent());
	}

	public static File fileCreator(String name) {
		if(name==null){
			
			return null;
		}
		else{
		File file = new File(name);
		if (!checkFileExist(file)) {
			try {
				file.createNewFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
			return file;
		} else
			return null;
		}
	}

	public static boolean fileWriter(File file, String content) {
		if (file == null) {
			System.out.println("File can not be created: either already exists or name is not valid");
			return false;
		} else {
			try {
				FileWriter fw = new FileWriter(file);
				PrintWriter out = new PrintWriter(fw);
				out.println(content);
				out.close();
				return true;
			} catch (IOException e) {
				System.err.format("IOException: %s%n");
				return false;
			}
		}
	}

	public static boolean checkFileExist(File file) {
		if (file.exists())
			return true;
		else
			return false;
	}

	public static String askForFileName() {
		System.out.println("Enter Filename");
		Scanner sc = new Scanner(System.in);
		return sc.nextLine();
	}

	public static String askForContent() {
		System.out.println("Enter the content");
		Scanner sc = new Scanner(System.in);
		return sc.nextLine();
	}

}
