/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.File;

public class AppTest {
	String fileName = "1234Test.txt";

    @AfterMethod
    public void deleteCreatedFile(){
        File file = new File(fileName);
        if(file.exists())
            file.delete();
    }

    @Test public void checkNewFileCreatedExists() {
        FileContentCreate classUnderTest = new FileContentCreate();
        classUnderTest.fileCreator(fileName);
        assertTrue(classUnderTest.checkFileExist(new File(fileName)));
    }
        
    @Test public void checkFileExistMessage() {
    	FileContentCreate classUnderTest = new FileContentCreate();
        classUnderTest.fileCreator(fileName);
        assertFalse(classUnderTest.fileWriter(classUnderTest.fileCreator(fileName), "absdfjdf"));
    }
    
    @Test public void checkWrietFileMethod() {
    	FileContentCreate classUnderTest = new FileContentCreate();
    	assertTrue(classUnderTest.fileWriter(classUnderTest.fileCreator(fileName), "absdfjdf"));
    }
    
    @Test public void checkCreateNullFile() {
    	FileContentCreate classUnderTest = new FileContentCreate();
    	assertFalse(classUnderTest.fileWriter(classUnderTest.fileCreator(null), "absdfjdf"));
    }

}
